### ISSUE TITLE
update the amazon app please

### ISSUE THREAD

**Issue by dd072370** [visnkmr/visnkmr#10]
I created this account just to write this reminder:

The version of app you have installed is 1.3A12i
Sorry, but it seems we have forgotten about the amazon appstore app. 

Please and thank you.

**Comment by Rontosh** [comment]
I created this account just to write this reminder:

The version of app you have installed is 1.3A12i
Sorry, but it seems we have forgotten about the amazon appstore app.

**Comment by visnkmr** [comment]
Please refer to existing threads about the issue  

- https://github.com/visnkmr/visnkmr/issues/8
- https://github.com/visnkmr/visnkmr/issues/6

**Comment by dd072370** [comment]
Thank you, much appreciated. I don't get it but thank you for your hard work.

**Comment by danewftree** [comment]
I created this account just to write this reminder:

The version of app you have installed is 1.3A12i
Sorry, but it seems we have forgotten about the amazon appstore app.

Please and thank you

**Comment by visnkmr** [comment]
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.
