### ISSUE TITLE
Background check 

### ISSUE THREAD

**Issue by Rattlers77** [visnkmr/visnkmr#11]
They haven't put it on the Amazon app store. This happens when you have an upgrade for this app

**Comment by artmck** [comment]
When will you add Background Check to the Amazon App store so it can be updated on our TV?

**Comment by visnkmr** [comment]
Please refer to existing threads about the issue  

- https://github.com/visnkmr/visnkmr/issues/8
- https://github.com/visnkmr/visnkmr/issues/6

**Comment by visnkmr** [comment]
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.

**Comment by Rattlers77** [comment]
Well it's not on my Amazon app store. I still have previous one. I click on it to update takes app store but it's not there. The previous one is.

**Comment by visnkmr** [comment]
Thanks for reporting.
Sometimes appstores do take some time to roll out updates based on region, I'll look into what can be done to prevent these in the future.
In the meantime, the update is already available on github (https://github.com/visnkmr/backgroundappslist/releases/latest)

**Comment by Rattlers77** [comment]
How do I download it straight from github to my firetv cube

**Comment by visnkmr** [comment]
If you prefer to download and use the APK then download the apk file to your phone/tablet and then transfer to fire tv using wireless file manager and install it from there.
