### ISSUE TITLE
Background Apps and process list not updated in Amazon app store?

### ISSUE THREAD

**Issue by ralp287** [visnkmr/visnkmr#12]
Are you going to update this app in the Amazon app store? As of 10/31/2023 still not updated.

**Comment by visnkmr** [comment]
Please refer to existing threads about the issue  

- https://github.com/visnkmr/visnkmr/issues/8
- https://github.com/visnkmr/visnkmr/issues/6

**Comment by JoeDoc29** [comment]
Friendly reminder to please update the background apps and process list for the Amazon app store

**Comment by visnkmr** [comment]
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.
