### ISSUE TITLE
Amazon App is not updating

### ISSUE THREAD

**Issue by volasko** [visnkmr/visnkmr#13]
I have version 1.3A12i on my firestick.  It is currently not functioning, as it needs an update.  

Thank you.

**Comment by visnkmr** [comment]
Please refer to existing threads about the issue  

- https://github.com/visnkmr/visnkmr/issues/8
- https://github.com/visnkmr/visnkmr/issues/6

**Comment by visnkmr** [comment]
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.
