### ISSUE TITLE
Background Process App

### ISSUE THREAD

**Issue by Dynamo1963** [visnkmr/visnkmr#17]

**Comment by Dynamo1963** [comment]
Comment on app says to remind you to update the App in Amazon Appstore app.

**Comment by visnkmr** [comment]
Please refer to existing threads about the issue  

- https://github.com/visnkmr/visnkmr/issues/8
- https://github.com/visnkmr/visnkmr/issues/6

**Comment by visnkmr** [comment]
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.

**Comment by Dynamo1963** [comment]
Thank you.  The update isn’t on Amazon app store yet. So I used the apk on the thread. Cheers
