### ISSUE TITLE
Your fire Stick verion

### ISSUE THREAD

**Issue by JediMike** [visnkmr/visnkmr#19]
![IMG_20231110_232107603.jpg](https://github.com/visnkmr/visnkmr/assets/115114095/6c8829bc-1582-4387-8291-6f48fa00f812)

**Comment by visnkmr** [comment]
Please refer https://github.com/visnkmr/visnkmr/issues/14#issuecomment-1799430622

**Comment by visnkmr** [comment]
Closing this as you have already mentioned in another thread.
