### ISSUE TITLE
Update App Reminder - Background App and Process List

### ISSUE THREAD

**Issue by CNDVidel** [visnkmr/visnkmr#27]
Hi. I'm seeing a message in the Background App and Process List app on my Android TV device stating to remind you to update it again. There's no update for it in the Google Play Store for Android TV. Thanks!

**Comment by Darknessangel27** [comment]
Hi. I'm seeing a message in the Background App and Process List app on my Amazon firestick/ appstore app stating to remind you to update it..

**Comment by DrumGuy68** [comment]
There is not an update on Google Play store. Where are we supposed to
update from?  I have an ANDROID TV not a Firestick

Regards



Tim Huntington
***@***.***
(203) 313-5656

**Comment by DrumGuy68** [comment]
Awesome, thanks for the update!

**Comment by CNDVidel** [comment]
Thank you!! 👍🏽😊
