### ISSUE TITLE
issues 

### ISSUE THREAD

**Issue by 1mediamaster** [visnkmr/visnkmr#34]
Background Apps and Process list:
Downloaded latest version and after a few days goes back to old version and this

**Comment by 1mediamaster** [comment]
Download 1.3A15i and after a few days app reverts back to 1.3G13i on its own
Happens over and over

**Comment by 1mediamaster** [comment]
Latest update reverts to 1.3G13i after 2 to 5 days

**Comment by visnkmr** [comment]
Hey, 
Could you please specify which device is this happening on and from which appstore you installed the application?

Thanks.

**Comment by 1mediamaster** [comment]
I am using Samsung galaxy A14 5g and buzz tv box 4500 (androids)
Downloading from your marketplace @visnkmr

**Comment by 1mediamaster** [comment]
Downloaded app-release.apk 2.09 MB
yesterday now I wait again to see if it reverts to 1.3G13i.

**Comment by visnkmr** [comment]
the version should not be reverting if you installed it from our appstore, seems strange maybe because of preinstalled appstore downgrading the app; anyway will monitor if more users report such issues.

**Comment by 1mediamaster** [comment]
Thank u boss
I'll keep you updated

**Comment by visnkmr** [comment]
Yes the issue seems to related to Google play auto updating the app per https://github.com/visnkmr/backgroundappslist/issues/713 . Will upload new version to our appstore tomorrow.

**Comment by 1mediamaster** [comment]
Great Job boss that was fast. Thank You so much
Love the app!

**Comment by 1mediamaster** [comment]
Hi...is new version available 
Ty

**Comment by visnkmr** [comment]
yes just updated it an hour ago, should be available now.

**Comment by 1mediamaster** [comment]
I'm on it...
Ty boss

**Comment by 1mediamaster** [comment]
I'm on it...
Ty boss

**Comment by 1mediamaster** [comment]
Issue resolved
