### ISSUE TITLE
Time NetSpeed monitor

### ISSUE THREAD

**Issue by Eric69bcn** [visnkmr/visnkmr#37]
Hola. Tengo 2 fire tv y hoy dia 31 de mayo no me funciona Time NetSpeed monitor. Pueden actualizarlo porfabor? Es de mucha utilidad y tener control de la hora gracias☺️🫶🏻
![IMG_20240531_121908](https://github.com/visnkmr/visnkmr/assets/171336345/b74ec041-26df-4370-8243-ccbab9f5020d)

**Comment by visnkmr** [comment]
Thanks for reminding me the update should now be available on our [appstore](https://visnkmr.github.io/appstore), the  amazon appstore one should be available in 1-3 days

**Comment by Eric69bcn** [comment]
Muchas gracias. Acabo de descargar la actualizacion. Mas tarde lo instalo en el fire tv. Muchas gracias y vendiciones😌☺️🫢🫶🏻✌🏻
