### ISSUE TITLE
Please update background apps 🙏

### ISSUE THREAD

**Issue by Shar85x** [visnkmr/visnkmr#6]
Hi can you please update background apps!? 

Thank you!  😊

**Comment by ObyDemon95** [comment]
Please update background apps!

**Comment by visnkmr** [comment]
Hey, 
Thanks for reporting.
An update is already available on github, it has been sent for review to Google Play and Amazon Appstore today. The appstore updates should arrive in a day, the github version is already available here. Sometimes appstores do take some time to roll out updates based on region, I'll look into what can be done to prevent these in the future.
Latest version on:

Fire TV, Tablet appstore is 1.3A13I,
Google play version is 1.3G12I.

**Comment by B-Hookken** [comment]
Thanks for fixing it.  Now, where do we find the the github version "available here?"

**Comment by visnkmr** [comment]
You can find the github version @ https://github.com/visnkmr/backgroundappslist/releases/latest

**Comment by B-Hookken** [comment]
Thank-you and Thanks for a terrific app, it makes app management so much easier. :)

**Comment by m22tanker** [comment]
Should the old version be uninstalled before installing the new one?

**Comment by visnkmr** [comment]
If you downloaded the already installed one from:
- google play it will need to be uninstalled
- amazon appstore it should update the existing one

**Comment by Shar85x** [comment]
@m22tanker could you please share the link so I can type it into my firestick 🙏

**Comment by m22tanker** [comment]
The link is posted earlier in this thread by visnkmr 18 hours ago

**Comment by visnkmr** [comment]
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.
