### ISSUE TITLE
Update reminder as requested 

### ISSUE THREAD

**Issue by Sportlife24** [visnkmr/visnkmr#8]
Please update background apps and processes. Message states that you may have forgotten about the Amazon Appstore app. Message appears on my Firestick 4k max and my Shield pro tv as well. 
Thank you

**Comment by m22tanker** [comment]
Same here. How about an update?

**Comment by Enkster46** [comment]
same here please

**Comment by Enkster46** [comment]
same here please

**Comment by m22tanker** [comment]
Update here: https://github.com/visnkmr/backgroundappslist/releases/tag/v1.3A13i

**Comment by Sportlife24** [comment]
Thank you

Sent from AT&T Yahoo Mail on Android 
 
  On Tue, Oct 24, 2023 at 7:43 PM, ***@***.***> wrote:   


Update here: https://github.com/visnkmr/backgroundappslist/releases/tag/v1.3A13i

**Comment by m22tanker** [comment]
You're most welcome

**Comment by tmb-github** [comment]
When I attempt to install it from the link provided above (https://github.com/visnkmr/backgroundappslist/releases/tag/v1.3A13i), the message "App not installed as package appears to be invalid" appears.
![Screenshot_20231025_084445_Package installer](https://github.com/visnkmr/visnkmr/assets/15718749/36855577-9edb-4765-aef1-73f6bc6864ba)

**Comment by m22tanker** [comment]
Try this https://github.com/visnkmr/backgroundappslist/releases/download/v1.3A13i/BAPL_1.3A13i.apk

**Comment by tmb-github** [comment]
@m22tanker Same message :-(

**Comment by m22tanker** [comment]
Sorry, it worked for me.

**Comment by Sportlife24** [comment]
Uninstall old then install new.

**Comment by tmb-github** [comment]
That worked. Thanks so much!

**Comment by visnkmr** [comment]
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.
