### ISSUE TITLE
Plz update amazon app

### ISSUE THREAD

**Issue by Bean5669** [visnkmr/visnkmr#9]
Please update the Amazon appstore app version 1.3A12i "background apps & process list"
Receiving a message to remind u to update the Amazon appstore app

**Comment by visnkmr** [comment]
Please refer to existing threads about the issue  

- https://github.com/visnkmr/visnkmr/issues/8
- https://github.com/visnkmr/visnkmr/issues/6

**Comment by visnkmr** [comment]
Closing this issue as the update should be available by now. Feel free to reopen if still facing the same issue.
